### ISSUE TITLE
Delete Record

### ISSUE THREAD

**Issue by ninjr** [kaamaru/Kohana-MongoDB-ODM#1]
I have a bunch of records i want to delete say

```
$odm = ODM::factory('ODM_Table')->find_all();

foreach ($odm as $o) {

  $o->delete();

}

```

this model exists and i can fetch and display records. Delete is providing me with an error ( method Model_ODM_Table::delete() does not exist)

![screen shot 2015-01-19 at 00 16 07](https://cloud.githubusercontent.com/assets/6792981/5794679/699ab1ea-9f70-11e4-87aa-8cee211879ec.png)

**Comment by kaamaru** [comment]
Try $o->remove(); I think I named the method that way be to be the same as the mongodb driver.

**Comment by ninjr** [comment]
Yeah i actually got it working later using the mongodb driver method which works fine it just confused me because your basic example page states use $o->delete(); that should be updated to avoid confusion
