### ISSUE TITLE
Dynamic Schema Issue

### ISSUE THREAD

**Issue by KishorThube** [kaamaru/Kohana-MongoDB-ODM#2]
protected $_schema = array(
		'_id'	=>  'MongoId',
		'employee_name'      => 'string',
		'department_name' => 'string',
		'address' => array(
			0=>array(
				'address_id' => 'int',
				'phone' => 'string'
			),
			1=>array(
				'address_id' => 'int',
				'phone' => 'string'
			),
		)
	);

I want to create a schema for a employee. As mention in the schema above the employee can have multiple addresses that i need to save using mongodb. But as per the current schema  i can only add two addresses if i want to add 3 address or more i need to added one more sub array as key value 2 in the current schema. Is there a way so that i can do this by dynamically. 

I tried to set $_schema = false; in the model but this also does not work for me. Can you please check this give me a reply asap.

Thanks.

**Comment by kaamaru** [comment]
Sorry for no reply, but I'm no longer maintaining this project.
